;/*FB_PKG_DELIM*/

__d("CometRoutePassthroughPropsContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext();g["default"]=b}),98);
__d("CometRouterParentRouteContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(null);g["default"]=b}),98);
__d("CometRouterStateContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext();g["default"]=b}),98);
__d("FDSCalloutContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(null);g["default"]=b}),98);
__d("react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils",[],(function(a,b,c,d,e,f){"use strict";function a(a){return a}f.NestedRelayEntryPoint=a}),66);
__d("NestedRelayEntryPointBuilderUtils",["react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils"],(function(a,b,c,d,e,f){"use strict";Object.keys(importNamespace("react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils")).forEach(function(a){if(a==="default"||a==="__esModule")return;f[a]=importNamespace("react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils")[a]})}),null);
__d("VideoShareDownstreamSignalTrackingTypes",[],(function(a,b,c,d,e,f){"use strict";a="downstream_video_share_data";f.DOWNSTREAM_VIDEO_SHARE_SESSION_STORAGE_KEY=a}),66);
__d("cometUniqueID",["ExecutionEnvironment"],(function(a,b,c,d,e,f,g){"use strict";var h,i=0,j;(h||c("ExecutionEnvironment")).canUseDOM?j="c":j="s";function a(){return"jsc_"+j+"_"+(i++).toString(36)}g["default"]=a}),98);
__d("getVideoShareDownstreamSignalTracking",["VideoShareDownstreamSignalTrackingTypes","WebStorage","gkx"],(function(a,b,c,d,e,f,g){"use strict";var h,i=1e3*60*60*4;function j(){var a;if(!c("gkx")("24"))return null;a=(a=(h||(h=c("WebStorage"))).getSessionStorage())==null?void 0:a.getItem(d("VideoShareDownstreamSignalTrackingTypes").DOWNSTREAM_VIDEO_SHARE_SESSION_STORAGE_KEY);if(a==null)return null;a=JSON.parse(a);return!a||a.downstream_share_session_start_time+i<Date.now()?null:a}function a(){var a=j();return!a?null:{downstream_share_session_id:a==null?void 0:a.downstream_share_session_id,downstream_share_session_origin_uri:a==null?void 0:a.downstream_share_session_origin_uri,downstream_share_session_start_time:a==null?void 0:a.downstream_share_session_start_time.toString()}}g.getVideoShareDownstreamSignalTrackingWithNumberStartTime=j;g.getVideoShareDownstreamSignalTracking=a}),98);
__d("intlList",["fbt","invariant","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i;a=i||b("react");var j={AND:"AND",NONE:"NONE",OR:"OR"},k={BULLET:"BULLET",COMMA:"COMMA",SEMICOLON:"SEMICOLON"};c=function(a,b,c){a=a.filter(Boolean);var d=a.length;if(d===0)return"";else if(d===1)return a[0];var e=a[d-1],f=a[0];for(var h=1;h<d-1;++h)switch(c){case k.SEMICOLON:f=g._("{previous items}; {following items}",[g._param("previous items",f),g._param("following items",a[h])]);break;case k.BULLET:f=g._("{previous items} \u2022 {following items}",[g._param("previous items",f),g._param("following items",a[h])]);break;default:f=g._("{previous items}, {following items}",[g._param("previous items",f),g._param("following items",a[h])])}return l(f,e,b||j.AND,c||k.COMMA)};function l(a,b,c,d){switch(c){case j.AND:return g._("{list of items} v\u00e0 {last item}",[g._param("list of items",a),g._param("last item",b)]);case j.OR:return g._("{list of items} ho\u1eb7c {last item}",[g._param("list of items",a),g._param("last item",b)]);case j.NONE:switch(d){case k.SEMICOLON:return g._("{previous items}; {last item}",[g._param("previous items",a),g._param("last item",b)]);case k.BULLET:return g._("{list of items} \u2022 {last item}",[g._param("list of items",a),g._param("last item",b)]);default:return g._("{list of items}, {last item}",[g._param("list of items",a),g._param("last item",b)])}default:h(0,568,c)}}c.DELIMITERS=k;c.CONJUNCTIONS=j;d=c;e.exports=d}),130);
__d("useBaseCallout",["BaseContextualLayerAnchorRootContext","BaseScrollableAreaContext","LayoutAnimationBoundaryContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useContext,j=b.useEffect,k=b.useId,l=b.useRef;function a(a,b,d,e){var f=i(c("BaseContextualLayerAnchorRootContext")),g=l(null),h=k(),m=k(),n=k(),o=i(c("BaseScrollableAreaContext")),p=i(c("LayoutAnimationBoundaryContext"));j(function(){if(d==null||g.current==null)return;if(a!=null&&b===!0){d.addCallout({anchorRef:g,anchorRootRefContext:f,animationContext:p,calloutID:h,calloutProps:a,contentID:m,contextualLayerProps:e,scrollableAreaContext:o,titleID:n});return function(){return d.removeCallout(h)}}},[p,f,d,h,m,n,a,b,o,e]);return{anchorRef:g,contentID:b?m:void 0,titleID:b?n:void 0}}g["default"]=a}),98);
__d("useCometRouterState",["CometRouterStateContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){return i(c("CometRouterStateContext"))}g["default"]=a}),98);
__d("useEffectOnce",["react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useEffect;function a(a){return i(a,[])}g["default"]=a}),98);
__d("useEmptyFunction",[],(function(a,b,c,d,e,f){"use strict";function a(){return}b=a;f["default"]=b}),66);
__d("useFDSCallout",["FDSCalloutContext","react","useBaseCallout"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(a,b){a=(a=a)!=null?a:{};var d=a.align,e=a.disableAutoAlign,f=a.disableAutoFlip,g=a.position;a=babelHelpers.objectWithoutPropertiesLoose(a,["align","disableAutoAlign","disableAutoFlip","position"]);var h=i(c("FDSCalloutContext"));b=c("useBaseCallout")(a,b,h,{align:d,disableAutoAlign:e,disableAutoFlip:f,position:g});h=b.anchorRef;d=b.contentID;e=b.titleID;return{anchorRef:h,contentID:d,titleID:a.title==null?void 0:e}}g["default"]=a}),98);
__d("useLayerKeyCommands",["CometLayerKeyCommandWidget"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=c("CometLayerKeyCommandWidget").useKeyCommands}),98);
__d("useParentRoute",["CometRouterParentRouteContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){return i(c("CometRouterParentRouteContext"))}g["default"]=a}),98);
__d("useRoutePassthroughProps",["CometRoutePassthroughPropsContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){return i(c("CometRoutePassthroughPropsContext"))}g["default"]=a}),98);