;/*FB_PKG_DELIM*/

__d("AdsPerfTiming",["performance"],(function(a,b,c,d,e,f,g){"use strict";var h;b=(h||(h=c("performance"))).timing&&(h||c("performance")).timing.fetchStart||a._cstart;g.start=b}),98);
__d("DesktopHscrollUnitEventConstants",[],(function(a,b,c,d,e,f){a="DesktopHScrollUnit/itemInserted";b="DesktopHScrollUnit/itemShown";c="DesktopHScrollUnit/HideIndividualItem";d="DesktopHScrollUnit/scrollItemBeforeXout";e="DesktopHScrollUnit/unhideIndividualItem";var g="logLastAdXout",h="onXoutIndividualItem";f.HSCROLL_ITEM_INSERTED_EVENT=a;f.HSCROLL_ITEM_SHOWN_EVENT=b;f.HSCROLL_ITEM_HIDE_EVENT=c;f.HSCROLL_ITEM_SCROLL_BEFORE_XOUT_EVENT=d;f.HSCROLL_ITEM_UNHIDE_EVENT=e;f.HSCROLL_LAST_ITEM_NFX_ACTION_TAKEN=g;f.HSCROLL_PAGER_ITEM_HIDE_EVENT=h}),66);
__d("KeyframesDownloadTracker",["NetworkStatus","Promise","XHRRequest","setTimeout"],(function(a,b,c,d,e,f,g){"use strict";var h,i=2,j=250;function a(a){return new(h||(h=b("Promise")))(function(b,d){var e=0,f,g=function f(){e++,new(c("XHRRequest"))(a).setMethod("GET").setResponseType("arraybuffer").setErrorHandler(function(a){var b=e<=i;b?c("setTimeout")(f,j):d(a)}).setAbortHandler(function(a){d(a)}).setResponseHandler(function(a){b(a)}).send()};if(c("NetworkStatus").isOnline())g();else{var h=function(a){a=a.online;a&&(g(),f.remove())};f=c("NetworkStatus").onChange(h)}})}g["default"]=a}),98);
__d("KeyframesVersionLogger",["BanzaiLogger","CurrentUser"],(function(a,b,c,d,e,f,g){"use strict";var h="KeyframesFramePerfLoggerConfig",i={appid:256281040558,isemployee:c("CurrentUser").isEmployee()?1:0},j={USE_LEGACY:"keyframes2_used",USE_MODERN:"keyframes3_used"};function k(a,b){c("BanzaiLogger").log(h,babelHelpers["extends"]({},i,{name:a,extras:(a=b)!=null?a:void 0}))}a={logLegacy:function(a){k(j.USE_LEGACY,a)},logModern:function(a){k(j.USE_MODERN,a)}};g.KeyframesVersionLogger=a}),98);
__d("RTLKeys",["Keys","Locale"],(function(a,b,c,d,e,f,g){var h=null;function i(){h===null&&(h=d("Locale").isRTL());return h}a=babelHelpers.objectWithoutPropertiesLoose(c("Keys"),["RIGHT","LEFT"]);var j=babelHelpers["extends"]({},a,{REAL_RIGHT:c("Keys").RIGHT,REAL_LEFT:c("Keys").LEFT,getLeft:function(){return i()?j.REAL_RIGHT:j.REAL_LEFT},getRight:function(){return i()?j.REAL_LEFT:j.REAL_RIGHT}});b=j;g["default"]=b}),98);
__d("isValidUniqueID",[],(function(a,b,c,d,e,f){function a(a){return a!==null&&a!==void 0&&a!==""&&(typeof a==="string"||typeof a==="number")}f["default"]=a}),66);
__d("SearchableEntry",["FbtResultBase","cr:556","isValidUniqueID"],(function(a,b,c,d,e,f,g){function h(a){if(a==null||a==="")return"";else if(typeof a==="string")return a;else if(a instanceof c("FbtResultBase"))return a.toString();else if(typeof a==="object"){a=b("cr:556").replaceJSONWrapper(a);if(b("cr:556").isHTML(a)){a=a.getRootNode();return a.textContent||a.innerText||""}else return""}else return""}a=function(){function a(a){this.valueOf=this.getUniqueID;c("isValidUniqueID")(a.uniqueID)||(a.uniqueID="null");this.$8=a.uniqueID+"";a.title instanceof c("FbtResultBase")&&(a.title=a.title.toString());a.title!=null&&typeof a.title==="string"||(a.title="null");this.$6=a.title;this.$3=a.order||0;this.$5=h(a.subtitle);this.$2=a.keywordString||"";this.$4=a.photo||"";this.$9=a.uri||"";this.$7=h(a.type);var b=a.auxiliaryData==null?{}:a.auxiliaryData;this.$1=b;this.$10=a.dataType||""}var b=a.prototype;b.getUniqueID=function(){return this.$8};b.getOrder=function(){return this.$3};b.getTitle=function(){return this.$6};b.getSubtitle=function(){return this.$5};b.getKeywordString=function(){return this.$2};b.getPhoto=function(){return this.$4};b.getURI=function(){return this.$9};b.getType=function(){return this.$7};b.getAuxiliaryData=function(){return this.$1};b.getDataType=function(){return this.$10};b.toPlainObject=function(){return{auxiliaryData:this.$1,keywordString:this.$2,order:this.$3,photo:this.$4,subtitle:this.$5,title:this.$6,type:this.$7,uniqueID:this.$8,uri:this.$9,dataType:this.$10}};return a}();g["default"]=a}),98);
__d("XThisControllerNoLongerExistsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/dcb/tcnle/",{t:{type:"String"}})}),null);
__d("ThisControllerNoLongerExists",["XControllerURIBuilder","XThisControllerNoLongerExistsController","jsRouteBuilder"],(function(a,b,c,d,e,f,g){"use strict";var h=function(b){babelHelpers.inheritsLoose(a,b);function a(a){var c;c=b.call(this,"/dcb/tcnle/",{})||this;c.$XControllerURIBuilderNoOpDead$p_1=a;return c}var d=a.prototype;d.__validateRequiredParamsExistence=function(){};d.__assertParamExists=function(a){};d.__setParam=function(a,b,c){return this};d.__setParamInt=function(a,b){};d.getRequest_LEGACY_UNTYPED=function(a){return a.setURI(this.getURI())};d.getURI=function(){return c("XThisControllerNoLongerExistsController").getURIBuilder().setString("t",this.$XControllerURIBuilderNoOpDead$p_1).getURI()};d.getLookasideURI=function(){return this.getURI()};return a}(c("XControllerURIBuilder"));function a(a){return c("XThisControllerNoLongerExistsController").getURIBuilder().setString("t",a).getURI()}function b(a){return new h(a)}function d(a){var b=c("jsRouteBuilder")("/dcb/tcnle/",{}),d={t:a};return{buildUri:function(){return b.buildUri(d)},buildUriNullable:function(){return b.buildUriNullable(d)},buildURL:function(){return b.buildURL(d)},buildURLStringDEPRECATED:function(){return b.buildURLStringDEPRECATED(d)}}}g.__DEADURI__=a;g.__DEADBUILDER__=b;g.__DEADROUTEBUILDER__=d}),98);
__d("destroyOnUnload",["cr:8905"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:8905")}),98);
__d("destroyOnUnloadWWW",["Run"],(function(a,b,c,d,e,f,g){function a(a){return d("Run").onLeave(a)}g["default"]=a}),98);
__d("getCentralImpressionTimeAfterRefresh",[],(function(a,b,c,d,e,f){"use strict";var g=null;window.addEventListener("load",function(){g=Date.now()},{passive:!0});function a(){return g!=null?Date.now()-g:0}f["default"]=a}),66);
__d("ghlTestUBT",["cr:1543261","cr:334"],(function(a,b,c,d,e,f,g){"use strict";b("cr:1543261")&&b("cr:1543261")(),g["default"]=b("cr:334")}),98);
__d("requireNUX",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){throw new Error("Cannot use raw untransformed requireNUX.")}f["default"]=a}),66);
__d("scrollTo",["debounce","emptyFunction"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b,d=a.onScrollComplete,e=a.onScrollStart,f=babelHelpers.objectWithoutPropertiesLoose(a,["onScrollComplete","onScrollStart"]);b=(b=a.top)!=null?b:window.pageYOffset;a=(a=a.left)!=null?a:window.pageXOffset;e&&e();if(window.pageYOffset===b&&window.pageXOffset===a){d&&d();return{dispose:c("emptyFunction")}}e=!1;try{var g=document.documentElement;if(g==null){d&&d();return{dispose:c("emptyFunction")}}g="scrollBehavior"in g.style;g?window.scrollTo(f):e=!0}catch(a){e=!0}if(e){window.scrollTo(a,b);d&&d();return{dispose:c("emptyFunction")}}var h,i=!1;d!=null&&(h=c("debounce")(function(){i=!0,window.removeEventListener("scroll",h),d&&d()},200),window.addEventListener("scroll",h,{passive:!0}),window.dispatchEvent(new Event("scroll")));return{dispose:function(){if(i)return;h&&h.reset();window.removeEventListener("scroll",h);window.scrollTo(window.pageYOffset,window.pageXOffset)}}}g["default"]=a}),98);
__d("useCustomEqualityMemo",["react","useUnsafeRef_DEPRECATED"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=(i||d("react")).useEffect;function a(a,b){var d=(h||(h=c("useUnsafeRef_DEPRECATED")))(a),e=b(d.current,a)?d.current:a;j(function(){d.current=e},[e]);return e}g["default"]=a}),98);